import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Folha de Pagamento",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="container flex h-14 max-w-screen-2xl items-center">
            <div className="mr-4 hidden md:flex">
              <a className="mr-6 flex items-center space-x-2" href="/">
                <span className="hidden font-bold sm:inline-block">
                  Nome+Logo
                </span>
              </a>
              <nav className="flex items-center gap-4 text-sm lg:gap-6">
                <a
                  className="transition-colors hover:text-foreground/80 text-foreground/60"
                  href="/"
                >
                  Inicio
                </a>
                <a
                  className="transition-colors hover:text-foreground/80 text-foreground/60"
                  href="/cadastro"
                >
                  Cadastro
                </a>
                <a
                  className="transition-colors hover:text-foreground/80 text-foreground/60"
                  href="/indicadores"
                >
                  Indicadores
                </a>
              </nav>
            </div>
          </div>
        </header>
        <div className="border-b">
          <div className="container flex-1 items-start grid gap-10">
            <div className="fixed top-14 z-30 -ml-2 h-[calc(100vh-3.5rem)] w-full shrink-0">
              <div className="relative py-6 lg:gap-10 lg:py-8 xl:grid xl:grid-cols-[1fr_300px]">
                <div>{children}</div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
